WITH RAW_PRICE AS
	(SELECT "Unnamed: 0" AS COURSE_ID,
			REPLACE(LIST_PRICE, '''', '"')::JSONB AS ORIGINAL_PRICE,
			REPLACE(PRICE, '''', '"')::JSONB AS DISCOUNT_PRICE
		FROM {{ ref('raw_price') }})
SELECT COURSE_ID,
	CAST(ORIGINAL_PRICE ->> 'amount' AS FLOAT) AS ORIGINAL_PRICE,
	CAST(DISCOUNT_PRICE ->> 'amount' AS FLOAT) AS DISCOUNT_PRICE
FROM RAW_PRICE