WITH SRC_COURSES AS
	(SELECT *
		FROM {{ ref('src_courses') }} AS SC
		LEFT JOIN {{ ref('src_prices') }} AS SP
		ON SC.ID = SP.COURSE_ID)
SELECT id AS course_id_fk,
	   CAST(visible_instructors->0->>'id' AS INTEGER) AS instructor_id_fk,
	   NUM_SUBSCRIBERS,
	   AVG_RATING,
	   NUM_REVIEWS,
	   NUM_PUBLISHED_LECTURES,
	   NUM_PUBLISHED_PRACTICE_TESTS,
	   CAST(TO_CHAR(CREATED,'YYYYMMDD') AS INTEGER) AS CREATED_DATE_FK,
	   CONTENT_LENGTH_PRACTICE_TEST_QUESTIONS,
	   CAST(REGEXP_REPLACE(CONTENT_INFO_SHORT, '[[:alpha:]]', '', 'g') AS FLOAT) AS CONTENT_TIME_HOURS,
	   ORIGINAL_PRICE,
	   DISCOUNT_PRICE
FROM SRC_COURSES
WHERE CAST(visible_instructors->0->>'id' AS INTEGER) IS NOT NULL
