WITH SRC_COURSES AS
	(SELECT *
		FROM {{ ref('src_courses') }})
SELECT ID AS COURSE_ID_PK,
	TITLE,
	URL,
	IS_PAID,
	IMG_URL,
	IS_PRACTICE_TEST_COURSE,
	HEADLINE,
	CAPTION_LOCALES,
	LOCALE,
	HAS_CLOSED_CAPTION,
	CAPTION_LANGUAGES,
	INSTRUCTIONAL_LEVEL,
	BADGES,
	CATEGORY_NAME,
	SUBCATEGORY_NAME
FROM (SELECT *,
	         ROW_NUMBER() OVER (PARTITION BY ID ORDER BY RANDOM()) AS row_num
	  FROM SRC_COURSES) t
WHERE row_num = 1